/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PointsService } from "../points.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PointsCreateInput } from "./PointsCreateInput";
import { Points } from "./Points";
import { PointsFindManyArgs } from "./PointsFindManyArgs";
import { PointsWhereUniqueInput } from "./PointsWhereUniqueInput";
import { PointsUpdateInput } from "./PointsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PointsControllerBase {
  constructor(
    protected readonly service: PointsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Points })
  @nestAccessControl.UseRoles({
    resource: "Points",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPoints(@common.Body() data: PointsCreateInput): Promise<Points> {
    return await this.service.createPoints({
      data: {
        ...data,

        branch: data.branch
          ? {
              connect: data.branch,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        branch: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        points: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Points] })
  @ApiNestedQuery(PointsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Points",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async pointsItems(@common.Req() request: Request): Promise<Points[]> {
    const args = plainToClass(PointsFindManyArgs, request.query);
    return this.service.pointsItems({
      ...args,
      select: {
        branch: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        points: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Points })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Points",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async points(
    @common.Param() params: PointsWhereUniqueInput
  ): Promise<Points | null> {
    const result = await this.service.points({
      where: params,
      select: {
        branch: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        points: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Points })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Points",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePoints(
    @common.Param() params: PointsWhereUniqueInput,
    @common.Body() data: PointsUpdateInput
  ): Promise<Points | null> {
    try {
      return await this.service.updatePoints({
        where: params,
        data: {
          ...data,

          branch: data.branch
            ? {
                connect: data.branch,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          branch: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          points: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Points })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Points",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePoints(
    @common.Param() params: PointsWhereUniqueInput
  ): Promise<Points | null> {
    try {
      return await this.service.deletePoints({
        where: params,
        select: {
          branch: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          points: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
